export const GET_NETWORKS = "GET_NETWORKS";
export const SET_ACTIVE_NETWORK = "SET_ACTIVE_NETWORK";
export const GET_STATIONS = "GET_STATIONS";
export const TOGGLE_STATION_LOADING = "TOGGLE_STATION_LOADING";
export const ADD_LIKED_STATION = "ADD_LIKED_STATION";
